(function(){'use strict';
  const $=id=>document.getElementById(id); const audio=$('radio'),body=document.body,overlay=$('broadcastStartOverlay'),card=$('broadcastNowCard'),cover=$('cover'),canvas=$('broadcastWaveform'),ctx=canvas.getContext('2d'),M=window.IntegratedPreviewModel;
  let tracks=[],index=0,currentWave=null,context,analyser,raf=0,fixtureState='standby',transitioning=false,metadataToken=0;
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const reduced=()=>body.classList.contains('reduced-motion')||(window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches);
  const clock=()=>{ $('localClock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false}); };
  const format=value=>{const seconds=Math.max(0,Number(value)||0);return Math.floor(seconds/60)+':'+String(Math.floor(seconds%60)).padStart(2,'0');};
  const localPath=(folder,file)=>'../../.local-media/emergency/'+folder+'/'+encodeURIComponent(file).replace(/%2F/g,'/');
  const trackData=(track,elapsed)=>({track_id:track.id,track_title:track.title,release_id:track.release_id,release_title:track.release_title,track_duration_seconds:track.duration_seconds,track_elapsed_seconds:elapsed,listeners:18,producer_profile:'MDK',producer_label:'fixture-derived local metadata',local_cover_url:localPath('covers',track.cover_file),release_text_source:'fixture',release_text_fragments:[{text:'fixture-derived local release annotation'}],transmission_log:tracks.filter(item=>item.id!==track.id).map((item,n)=>({started_at:Date.now()-(n+1)*3600000,release_id:item.release_id,release_title:item.release_title,track_title:item.title,track_id:item.id}))});
  function setState(state){fixtureState=state;body.dataset.broadcastState=state;card.dataset.connection=state;const labels={standby:'STANDBY · USER GESTURE REQUIRED',acquiring:'ACQUIRING SIGNAL',transmitting:'TRANSMITTING · FIXTURE AUDIO',incoming:'INCOMING SIGNAL',metadata:'METADATA TEMPORARILY UNAVAILABLE',unavailable:'AUDIO UNAVAILABLE'};$('broadcastStateText').textContent=labels[state]||labels.standby;$('statusLine').textContent='status: '+(labels[state]||labels.standby).toLowerCase();$('nowLabel').textContent=state==='incoming'?'INCOMING SIGNAL':'NOW TRANSMITTING';overlay.hidden=state!=='standby';}
  async function waveform(track){if(track._wave)return track._wave;const response=await fetch('../player-widget-lab/'+track.waveform);const result=await response.json();if(!result.peaks||!result.rms)throw new Error('invalid waveform');track._wave=result;return result;}
  function setCover(track){cover.src=localPath('covers',track.cover_file);cover.alt=track.release_title+' cover';}
  function renderMetadata(track,mode=fixtureState){const missing=mode==='metadata';$('track').textContent=missing?'Metadata unavailable':track.title;$('releaseId').textContent=missing?'—':track.release_id;$('release').textContent=missing?'Metadata temporarily unavailable':track.release_title;$('trackNumber').textContent=missing?'—':String(track.track_number).padStart(2,'0');setCover(track);}
  function canvasSize(){const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1),width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}ctx.setTransform(ratio,0,0,ratio,0,0);return{width:rect.width,height:rect.height};}
  function accent(){const raw=getComputedStyle(body).getPropertyValue('--cover-accent-1').trim().replace(/,/g,' ');const parts=raw.split(/\s+/).map(Number).filter(Number.isFinite);return parts.length>=3?parts.slice(0,3):[117,255,194];}
  function draw(){const size=canvasSize();if(!currentWave||size.width<=1||size.height<=1)return;const track=tracks[index],duration=Number.isFinite(audio.duration)?audio.duration:track.duration_seconds,progress=M.progressRatio(audio.currentTime||0,duration),[r,g,b]=accent(),count=Math.max(96,Math.min(220,Math.floor(size.width/3))),peaks=M.downsample(currentWave.peaks,count),rms=M.downsample(currentWave.rms,count),step=size.width/count,center=size.height/2,active=fixtureState==='transmitting'||fixtureState==='incoming';ctx.clearRect(0,0,size.width,size.height);for(let i=0;i<count;i++){const played=i/count<=progress,x=i*step+step/2,peak=Math.max(1.5,peaks[i]*size.height*.39),bodyPeak=Math.max(1.5,rms[i]*size.height*.34);ctx.strokeStyle=played&&active?'rgb('+r+' '+g+' '+b+')':active?'rgb(59 91 74)':'rgb(63 78 69)';ctx.globalAlpha=active?(played?.9:.48):.38;ctx.lineWidth=Math.max(1.7,Math.min(2.5,step*.5));ctx.beginPath();ctx.moveTo(x,center-peak);ctx.lineTo(x,center+peak);ctx.stroke();if(bodyPeak>peak*.7){ctx.globalAlpha*=.3;ctx.beginPath();ctx.moveTo(x,center-bodyPeak);ctx.lineTo(x,center+bodyPeak);ctx.stroke();}}
    ctx.globalAlpha=1;const head=size.width*progress;ctx.strokeStyle=active?'rgba(237,245,239,.78)':'rgba(183,205,191,.28)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(head,0);ctx.lineTo(head,size.height);ctx.stroke();const marker=Math.max(4,size.width*Math.min(.035,8/track.duration_seconds));ctx.fillStyle='rgba(255,208,120,.09)';ctx.fillRect(size.width-marker,0,marker,size.height);ctx.strokeStyle='rgba(255,208,120,.52)';ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(size.width-marker,0);ctx.lineTo(size.width-marker,size.height);ctx.stroke();ctx.setLineDash([]);}
  function syncTime(){if(!tracks.length)return;const track=tracks[index],duration=Number.isFinite(audio.duration)?audio.duration:track.duration_seconds,elapsed=audio.currentTime||0;$('elapsed').textContent=format(elapsed);$('remaining').textContent='−'+format(Math.max(0,duration-elapsed));draw();if(window.UIWidgets)window.UIWidgets.tick(trackData(track,elapsed),null,elapsed);}
  async function commitTrack(next,{resetAudio=true,mode=fixtureState}={}){index=(next+tracks.length)%tracks.length;$('fixtureTrack').value=String(index);currentWave=await waveform(tracks[index]);if(resetAudio){audio.src=localPath('tracks',tracks[index].audio_file);audio.load();}renderMetadata(tracks[index],mode);syncTime();if(window.UIWidgets)window.UIWidgets.syncTelemetry(trackData(tracks[index],audio.currentTime||0),audio.currentTime||0);}
  function clearTransition(){card.classList.remove('transition-forecast','transition-flicker','transition-persistence','transition-writing','transition-wave','transition-simple');$('incomingSignal').hidden=true;cover.classList.remove('cover-out','cover-in');transitioning=false;}
  async function typeTitle(value){const node=$('track');node.textContent='';for(let i=0;i<value.length;i++){node.textContent+=value[i];if(i===3)$('metadataBand').style.opacity='1';await sleep(22);}}
  async function simpleTransition(next,wasPlaying){card.classList.add('transition-simple');await sleep(160);await commitTrack(next,{mode:'transmitting'});if(wasPlaying){try{await audio.play();}catch(_){}}await sleep(120);clearTransition();setState('transmitting');}
  async function transitionTo(next){if(transitioning||next===index)return;transitioning=true;const wasPlaying=!audio.paused,nextTrack=tracks[next],nextWave=await waveform(nextTrack);if(reduced()){await simpleTransition(next,wasPlaying);return;}setState('incoming');$('incomingSignal').hidden=false;card.classList.add('transition-forecast');await sleep(700);card.classList.replace('transition-forecast','transition-flicker');await sleep(300);card.classList.replace('transition-flicker','transition-persistence');cover.classList.add('cover-out');await sleep(340);audio.pause();index=next;$('fixtureTrack').value=String(index);currentWave=nextWave;audio.src=localPath('tracks',tracks[index].audio_file);audio.load();setCover(nextTrack);cover.classList.remove('cover-out');cover.classList.add('cover-in');$('metadataBand').style.opacity='0';$('releaseId').textContent=nextTrack.release_id;$('release').textContent=nextTrack.release_title;$('trackNumber').textContent=String(nextTrack.track_number).padStart(2,'0');card.classList.replace('transition-persistence','transition-writing');await typeTitle(nextTrack.title);$('metadataBand').style.opacity='1';card.classList.replace('transition-writing','transition-wave');syncTime();if(window.UIWidgets)window.UIWidgets.syncTelemetry(trackData(nextTrack,0),0);await sleep(850);if(wasPlaying){try{await audio.play();}catch(_){}}clearTransition();setState('transmitting');}
  async function engage(){if(fixtureState==='unavailable')return setState('unavailable');setState('acquiring');try{await audio.play();setState('transmitting');setupSpectrum();}catch(_){setState('standby');}}
  function setupSpectrum(){if(context)return;try{context=new AudioContext();const source=context.createMediaElementSource(audio);analyser=context.createAnalyser();analyser.fftSize=128;source.connect(analyser);analyser.connect(context.destination);drawSpectrum();}catch(_){}}
  function drawSpectrum(){const canvas=$('spectrum'),rect=canvas.getBoundingClientRect();if(rect.width&&rect.height){const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const context2=canvas.getContext('2d');context2.setTransform(ratio,0,0,ratio,0,0);context2.clearRect(0,0,rect.width,rect.height);const values=analyser?new Uint8Array(analyser.frequencyBinCount):[],color=accent().join(' ');if(analyser)analyser.getByteFrequencyData(values);for(let i=0;i<32;i++){const value=values.length?values[i]:0,height=Math.max(2,value/255*rect.height*.9);context2.fillStyle='rgb('+color+')';context2.globalAlpha=.2+value/510;context2.fillRect(i*rect.width/32,rect.height-height,Math.max(1,rect.width/32-2),height);}context2.globalAlpha=1;}raf=requestAnimationFrame(drawSpectrum);}
  function tick(){syncTime();requestAnimationFrame(tick);}async function init(){const response=await fetch('../player-widget-lab/fixtures.json'),fixture=await response.json();tracks=fixture.tracks;tracks.forEach((track,n)=>{const option=document.createElement('option');option.value=n;option.textContent=track.title;$('fixtureTrack').append(option);});await commitTrack(0,{mode:'standby'});setState('standby');clock();setInterval(clock,30000);tick();}
  overlay.addEventListener('pointerdown',engage);window.addEventListener('keydown',event=>{if(!overlay.hidden&&(event.key==='Enter'||event.key===' ')){event.preventDefault();engage();}});$('fixtureTrack').addEventListener('change',event=>transitionTo(Number(event.target.value)));$('fixtureState').addEventListener('change',event=>{const state=event.target.value;if(state==='normal'){setState(audio.paused?'standby':'transmitting');renderMetadata(tracks[index],fixtureState);}else{if(state==='unavailable')audio.pause();setState(state);renderMetadata(tracks[index],state);}syncTime();});$('reducedMotion').addEventListener('change',event=>body.classList.toggle('reduced-motion',event.target.checked));audio.addEventListener('ended',()=>transitionTo((index+1)%tracks.length));audio.addEventListener('error',()=>setState('unavailable'));window.addEventListener('mdk:palette-changed',draw);window.addEventListener('beforeunload',()=>cancelAnimationFrame(raf));init().catch(()=>setState('unavailable'));
}());
