'use strict';
const assert=require('node:assert/strict');const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const ROOT=__dirname,REPO=path.resolve(ROOT,'../..');const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');const css=fs.readFileSync(path.join(ROOT,'prototype.css'),'utf8');const app=fs.readFileSync(path.join(ROOT,'prototype.js'),'utf8');const widgets=fs.readFileSync(path.join(REPO,'web/ui-widgets.js'),'utf8');const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(REPO,file))).digest('hex');const has=(text,value)=>assert.ok(text.includes(value),value);
test('Broadcast uses the Radio-derived title metadata and single Refined Thin waveform',()=>{for(const id of ['track','metadataBand','releaseId','release','trackNumber','broadcastWaveform','elapsed','remaining'])has(html,'id="'+id+'"');for(const old of ['progressBar','progressHead','refined-progress'])assert.ok(!html.includes(old),old);has(html,'preview-model.js');has(app,'M.downsample(currentWave.peaks');has(app,'M.progressRatio');});
test('Broadcast retains its passive lower functional area and excludes Radio controls',()=>{for(const marker of ['broadcast-listen','broadcast-system-widgets'])has(html,marker);for(const marker of ['SIGNAL TRANSIT','RECEIVER ARRAY','TEMPORAL DRIFT'])has(widgets,marker);for(const forbidden of ['previewVolume','GET THIS TRACK','LISTEN OPTIONS','SUPPORT','connectButton','coverDialog'])assert.ok(!html.includes(forbidden),forbidden);});
test('fixture identity changes activate approved transition markers',()=>{for(const marker of ['transition-forecast','transition-flicker','transition-persistence','transition-writing','transition-wave','cover-out','cover-in','incomingSignal'])has(app,marker);has(app,"$('fixtureTrack').addEventListener('change',event=>transitionTo");has(app,"setState('incoming')");has(app,'typeTitle(nextTrack.title)');});
test('reduced motion uses the opacity fallback instead of typed reveal and sweep',()=>{has(app,'if(reduced()){await simpleTransition');has(css,'.transition-simple');has(css,'prefers-reduced-motion:reduce');has(css,'.reduced-motion *');});
test('cover is non-interactive and one audio element remains persistent',()=>{assert.equal((html.match(/<audio /g)||[]).length,1);has(html,'data-role="persistent-primary-audio"');has(css,'pointer-events:none');has(app,"const audio=$('radio')");for(const forbidden of ["createElement('audio')",'new Audio(','replaceChildren(audio'])assert.ok(!app.includes(forbidden),forbidden);});
test('desktop instruments remain one row and mobile stacks without hiding waveform',()=>{has(css,'broadcast-system-widgets{grid-template-columns:repeat(3,minmax(0,1fr))');has(css,'#broadcastWaveform{height:64px}');has(css,'broadcast-system-widgets{grid-template-columns:1fr}');has(css,'overflow-y:auto');has(css,'.terminal{max-height:none;overflow:visible');});
test('state language and standby interaction remain present',()=>{for(const state of ['standby','acquiring','transmitting','incoming','metadata','unavailable'])has(app,state);has(app,"overlay.addEventListener('pointerdown',engage)");has(app,"event.key==='Enter'||event.key===' '");});

test('waveform scan is contained by its dedicated viewport',()=>{has(html,'class="waveform-viewport"');has(css,'.waveform-viewport{position:relative;overflow:hidden;overflow:clip');has(css,'.waveform-viewport::after{content:"";position:absolute');has(css,'.transition-forecast .waveform-viewport::after');assert.ok(!css.includes('.transition-forecast .broadcast-waveform::after'));assert.ok(!css.includes('.broadcast-now-card::after{opacity:1;animation:acquisition-sweep'));});
test('production and approved Radio artifact remain byte-identical',()=>{const expected={'web/index.html':'6f6256e2e709559c698502a85a26679f9b584022f1631cbf3fb383d00b1c446b','web/styles.css':'4f4de5f5c7113d6894cdfdd074882eda025053cb6a05b256bb092da0c510f2f0','web/app.js':'a0654fd7883058d4eb658c450c2cebfdc5984715a0561cdc17bffdb5eff505b4','.artifacts/player-integrated-preview/index.html':'9ce8e2717e80f4b10d1c86a319fe2cf5c1763842a5fee795caf6302676819bf3','.artifacts/player-integrated-preview/preview.css':'9196353884c19850c15020170f0252504396565e168f4b823890cc9193491dd5','.artifacts/player-integrated-preview/preview.js':'da601df0080e15ec423ed42d1b58fef6e7b61e0a092bab6192149ec8f760804e','.artifacts/player-integrated-preview/preview-model.js':'e81a423610364a62ee9103508a518a3915b6bb40b8ab0792a947246a824ac421'};for(const[file,value]of Object.entries(expected))assert.equal(hash(file),value,file);});
